[project]
name = "enterprise-brain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "apscheduler",
    "chromadb",
    "dashscope",
    "fastapi",
    "fpdf2",
    "graphviz>=0.21",
    "jieba",
    "langchain",
    "langchain-community",
    "langchain-deepseek",
    "langchain-mineru>=0.1.3",
    "langchain-openai",
    "langchain-tavily",
    "langgraph",
    "langgraph-checkpoint-sqlite",
    "langgraph-checkpoint-postgres",
    "mcp",
    "matplotlib",
    "modelscope>=1.37.1",
    "olefile>=0.47",
    "ollama",
    "openai",
    "openpyxl",
    "pandas",
    "plotly>=6.8.0",
    "pydantic",
    "python-docx>=1.2.0",
    "python-dotenv",
    "python-multipart",
    "rank-bm25>=0.2.2",
    "sentence-transformers>=5.6.0",
    "torch>=2.12.0",
    "uvicorn",
    "wordcloud",
    "xlsxwriter",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
