"""R22 (docs/handoff/2026-09-15-backend-followup-requests.md section 18, restated in section 22).

An index version is the unit an embedding profile is bound to: ``embedding_model`` plus
``dimension``. These tests pin what makes the binding real rather than decorative -- a version
carries both values, either one changing cannot reuse the old version, two profiles never serve
the same query, and a record written before the binding existed loads as *unknown* instead of
quietly claiming whatever model is configured now.
"""
from __future__ import annotations

import json

import pytest

MODEL_A = "nomic-embed-text"
MODEL_B = "bge-m3"
DIM_NARROW = 384
DIM_WIDE = 768
INDEX = "document:policy.txt"

# Written by app/rag/indexing.py at baseline a6e2972 and pasted verbatim: the shape an
# existing deployment already has on disk. Ten keys, no embedding_model, no dimension. It is
# generated by the real pre-R22 code rather than hand-typed, so the compatibility claim below
# is about that code and not about what this file hoped it looked like.
LEGACY_METADATA = {
    "current": {
        "document:finance.txt": "document:finance.txt:v33a012c5bbfa4ad6983c6f02a2e3545c",
        "document:policy.txt": "document:policy.txt:v89145f26783746cfb4e05a794cfe740c",
    },
    "versions": [
        {
            "backend": "chroma",
            "checksum": "a" * 64,
            "chunk_count": 3,
            "created_at": "2026-09-18T02:53:29.171867+00:00",
            "index_id": "document:policy.txt",
            "index_version_id": "document:policy.txt:v89145f26783746cfb4e05a794cfe740c",
            "published_at": "2026-09-18T02:53:29.174796+00:00",
            "retirement": False,
            "source_version_id": "policy.txt|v1",
            "status": "published",
        },
        {
            "backend": "chroma",
            "checksum": "b" * 64,
            "chunk_count": 2,
            "created_at": "2026-09-18T02:53:29.175838+00:00",
            "index_id": "document:finance.txt",
            "index_version_id": "document:finance.txt:v33a012c5bbfa4ad6983c6f02a2e3545c",
            "published_at": "2026-09-18T02:53:29.178080+00:00",
            "retirement": False,
            "source_version_id": "finance.txt|v2",
            "status": "published",
        },
    ],
}


def _scope(model, dimension):
    from app.rag.indexing import EmbeddingScope

    return EmbeddingScope(model, dimension)


def _registry(tmp_path, *, model=MODEL_A, dimension=DIM_WIDE):
    from app.rag.indexing import IndexRegistry

    return IndexRegistry(tmp_path / "indexes.json", scope=_scope(model, dimension))


def _load_legacy(tmp_path, registry):
    """Point a registry at the baseline file and re-read it, the way the field would."""
    path = tmp_path / "legacy-indexes.json"
    path.write_text(json.dumps(LEGACY_METADATA), encoding="utf-8")
    registry.metadata_path = path
    registry._load()
    return path


def _version(registry, *, index_id=INDEX, source="policy.txt|v1", chunks=3, checksum="a" * 64):
    return registry.create_version(
        index_id=index_id,
        source_version_id=source,
        backend="chroma",
        chunk_count=chunks,
        checksum=checksum,
    )

# ------------------------------------------------- 1. the version carries the profile
def test_a_version_records_which_model_and_width_produced_it(tmp_path):
    registry = _registry(tmp_path, model=MODEL_B, dimension=DIM_NARROW)
    version = _version(registry)
    registry.publish(version.index_version_id)

    assert (version.embedding_model, version.dimension) == (MODEL_B, DIM_NARROW)
    assert version.scope == _scope(MODEL_B, DIM_NARROW)

    reopened = _registry(tmp_path, model=MODEL_B, dimension=DIM_NARROW)
    persisted = reopened.current(INDEX)
    assert (persisted.embedding_model, persisted.dimension) == (MODEL_B, DIM_NARROW)


def test_a_version_that_names_no_profile_inherits_the_configured_one(tmp_path):
    registry = _registry(tmp_path, model=MODEL_A, dimension=DIM_WIDE)
    version = _version(registry)

    assert version.embedding_model == MODEL_A
    assert version.dimension == DIM_WIDE


def test_naming_only_the_width_still_keeps_the_configured_model(tmp_path):
    from app.rag.indexing import IndexScopeError

    # Naming one axis must not be read as "don't care about the other": a query that only
    # knows its width still cannot borrow a different model's vectors.
    registry = _registry(tmp_path, model=MODEL_A, dimension=DIM_WIDE)
    version = registry.create_version(
        index_id=INDEX,
        source_version_id="policy.txt|v1",
        backend="chroma",
        chunk_count=1,
        checksum="a" * 64,
        dimension=DIM_NARROW,
    )

    assert version.dimension == DIM_NARROW
    assert version.embedding_model == MODEL_A
    # Never published, so no width may search it.
    assert registry.queryable_version_ids(dimension=DIM_WIDE) == frozenset()
    assert registry.queryable_version_ids(dimension=DIM_NARROW) == frozenset()
    # It cannot be published under the configured 768 either: half a match is not a match.
    with pytest.raises(IndexScopeError):
        registry.publish(version.index_version_id)

    registry._fixed_scope = _scope(MODEL_A, DIM_NARROW)
    registry.publish(version.index_version_id)
    assert registry.queryable_version_ids(dimension=DIM_NARROW) == frozenset({version.index_version_id})
    assert registry.queryable_version_ids(dimension=DIM_WIDE) == frozenset()


def test_an_unusable_dimension_is_refused_rather_than_recorded_as_unknown(tmp_path):
    registry = _registry(tmp_path)

    for bad in (0, -768, "wide"):
        with pytest.raises(ValueError, match="positive integer"):
            registry.create_version(
                index_id=INDEX,
                source_version_id="policy.txt|v1",
                backend="chroma",
                chunk_count=1,
                checksum="a" * 64,
                dimension=bad,
            )


# ------------------------------- 2. either axis changing cannot reuse the old version
def test_a_dimension_change_cannot_revalidate_or_republish_the_old_version(tmp_path):
    from app.rag.indexing import CODE_DIMENSION_DRIFT, CODE_SCOPE_MISMATCH, IndexScopeError

    registry = _registry(tmp_path, dimension=DIM_NARROW)
    old = _version(registry)
    registry.publish(old.index_version_id)

    # The operator changes the embedder. Nothing restarts: the registry reads the profile on
    # demand, so the change bites at the next decision rather than at the next deploy.
    registry._fixed_scope = _scope(MODEL_A, DIM_WIDE)

    with pytest.raises(IndexScopeError) as refused:
        registry.validate(old.index_version_id)
    assert refused.value.code == CODE_SCOPE_MISMATCH
    assert CODE_DIMENSION_DRIFT in refused.value.codes
    with pytest.raises(IndexScopeError):
        registry.publish(old.index_version_id)

    # The only way forward is a new version, and producing one does not destroy the old.
    rebuilt = _version(registry, checksum="a" * 64)
    registry.publish(rebuilt.index_version_id)
    assert rebuilt.index_version_id != old.index_version_id
    assert registry.current(INDEX).index_version_id == rebuilt.index_version_id
    assert registry.current(INDEX).dimension == DIM_WIDE
    assert registry._versions[old.index_version_id].status == "superseded"


def test_a_model_change_with_an_identical_payload_still_lands_on_a_new_version(tmp_path):
    """Same document, same chunks, same checksum -- only the embedder moved.

    This is the case a content hash cannot see: nothing about the text changed, so a registry
    that did not bind the profile would keep pointing at vectors another model computed, and
    every retrieval number would quietly describe a different library.
    """
    registry = _registry(tmp_path, model=MODEL_A)
    old = _version(registry)
    registry.publish(old.index_version_id)

    registry._fixed_scope = _scope(MODEL_B, DIM_WIDE)
    rebuilt = _version(registry)
    registry.publish(rebuilt.index_version_id)

    assert rebuilt.checksum == old.checksum
    assert rebuilt.index_version_id != old.index_version_id
    assert rebuilt.embedding_model == MODEL_B
    assert registry.queryable_version_ids(index_id=INDEX) == frozenset({rebuilt.index_version_id})
    assert old.index_version_id not in registry.queryable_version_ids()
    assert registry._versions[old.index_version_id].status == "superseded"

# ------------------------------------------- 3. two profiles never answer one query
def test_a_current_version_is_refused_when_the_query_uses_another_width(tmp_path):
    from app.rag.indexing import CODE_SCOPE_MISMATCH, IndexScopeError

    registry = _registry(tmp_path, dimension=DIM_WIDE)
    old = _version(registry, source="policy.txt|v1")
    registry.publish(old.index_version_id)

    registry._fixed_scope = _scope(MODEL_A, DIM_NARROW)
    narrow = _version(registry, source="policy.txt|v2")
    registry.publish(narrow.index_version_id)

    assert registry.queryable_version_ids(dimension=DIM_NARROW) == frozenset({narrow.index_version_id})
    assert registry.queryable_version_ids(dimension=DIM_WIDE) == frozenset({old.index_version_id})
    with pytest.raises(IndexScopeError) as refused:
        registry.queryable_version(INDEX, dimension=DIM_WIDE)
    assert refused.value.code == CODE_SCOPE_MISMATCH
    # The unscoped bookkeeping read still answers, so reporting never becomes an outage.
    assert registry.current(INDEX).index_version_id == narrow.index_version_id


def test_cross_dimension_hits_are_dropped_rather_than_ranked(tmp_path):
    """Zero hits from the other profile, measured over the records themselves."""
    from app.rag.indexing import retain_queryable

    registry = _registry(tmp_path, dimension=DIM_WIDE)
    old = _version(registry, source="policy.txt|v1")
    registry.publish(old.index_version_id)
    registry._fixed_scope = _scope(MODEL_A, DIM_NARROW)
    current = _version(registry, source="policy.txt|v2")
    registry.publish(current.index_version_id)

    hits = [
        {"index_version_id": old.index_version_id, "content": "stale, other width"},
        {"index_version_id": current.index_version_id, "content": "right width"},
        {"content": "a hit that names no version at all"},
    ]

    kept = retain_queryable(registry, hits, dimension=DIM_NARROW)
    assert [row["content"] for row in kept] == ["right width"]
    assert sum(1 for row in kept if row["index_version_id"] == old.index_version_id) == 0

    # Ask for a width nothing publishes at and the answer is empty, not the old vectors:
    # "there is nothing under that profile" is the only honest reply.
    assert retain_queryable(registry, hits, dimension=1024) == []


def test_rollback_cannot_switch_an_index_back_to_another_widths_version(tmp_path):
    from app.rag.indexing import CODE_SCOPE_MISMATCH, IndexScopeError

    registry = _registry(tmp_path, dimension=DIM_NARROW)
    narrow = _version(registry, source="policy.txt|v1")
    registry.publish(narrow.index_version_id)
    registry._fixed_scope = _scope(MODEL_A, DIM_WIDE)
    wide = _version(registry, source="policy.txt|v2")
    registry.publish(wide.index_version_id)

    with pytest.raises(IndexScopeError) as refused:
        registry.rollback(INDEX, narrow.index_version_id)
    assert refused.value.code == CODE_SCOPE_MISMATCH
    assert registry.current(INDEX).index_version_id == wide.index_version_id

    # Rolling the *configuration* back first makes it a like-for-like restore again.
    registry._fixed_scope = _scope(MODEL_A, DIM_NARROW)
    restored = registry.rollback(INDEX, narrow.index_version_id)
    assert restored.index_version_id == narrow.index_version_id


def test_discard_refuses_to_erase_the_other_profiles_rollback_target(tmp_path):
    from app.rag.indexing import CODE_SCOPE_MISMATCH, IndexScopeError

    registry = _registry(tmp_path, dimension=DIM_NARROW)
    narrow = _version(registry, source="policy.txt|v1")
    registry.publish(narrow.index_version_id)
    registry._fixed_scope = _scope(MODEL_A, DIM_WIDE)

    with pytest.raises(IndexScopeError) as refused:
        registry.discard(narrow.index_version_id)
    assert refused.value.code == CODE_SCOPE_MISMATCH
    assert narrow.index_version_id in registry._versions
    # A refusal must not have touched the current pointer either.
    assert registry.current(INDEX).index_version_id == narrow.index_version_id


# ---------------------------------------------- 4. legacy records stay explicitly unknown
def test_a_record_without_a_profile_loads_and_is_not_blessed_with_todays_model(tmp_path):
    registry = _registry(tmp_path, model=MODEL_A, dimension=DIM_WIDE)
    _load_legacy(tmp_path, registry)

    version = registry.current(INDEX)
    assert version.index_version_id == LEGACY_METADATA["current"][INDEX]
    assert version.embedding_model is None
    assert version.dimension is None
    assert not version.scope.known
    assert str(version.scope) == "unknown/unknown"
    # The explicit negative: a missing field must not resolve to the live configuration.
    assert version.embedding_model != registry.scope.embedding_model


def test_a_legacy_version_cannot_be_validated_published_or_rolled_back(tmp_path):
    from app.rag.indexing import CODE_SCOPE_UNKNOWN, IndexScopeError

    registry = _registry(tmp_path)
    _load_legacy(tmp_path, registry)
    legacy_id = LEGACY_METADATA["current"][INDEX]

    for call in (
        lambda: registry.validate(legacy_id),
        lambda: registry.publish(legacy_id),
        lambda: registry.rollback(INDEX, legacy_id),
    ):
        with pytest.raises(IndexScopeError) as refused:
            call()
        assert refused.value.code == CODE_SCOPE_UNKNOWN

    assert registry.queryable_version_ids(dimension=DIM_WIDE) == frozenset()
    assert registry.queryable_version_ids() == frozenset()
    with pytest.raises(IndexScopeError):
        registry.queryable_version(INDEX, dimension=DIM_WIDE)


def test_a_new_publication_supersedes_a_legacy_version_without_needing_its_profile(tmp_path):
    """Re-uploading one document fixes that document's record; it does not fake the others."""
    registry = _registry(tmp_path)
    _load_legacy(tmp_path, registry)
    legacy_id = LEGACY_METADATA["current"][INDEX]

    rebuilt = _version(registry, source="policy.txt|v9", chunks=1, checksum="c" * 64)
    registry.publish(rebuilt.index_version_id)

    assert registry.current(INDEX).index_version_id == rebuilt.index_version_id
    assert registry.current(INDEX).dimension == DIM_WIDE
    assert registry._versions[legacy_id].status == "superseded"
    assert registry._versions[legacy_id].embedding_model is None
    # The untouched legacy index is still readable, and still refuses to answer a query.
    assert registry.current("document:finance.txt").embedding_model is None
    assert registry.queryable_version_ids(index_id="document:finance.txt") == frozenset()


def test_a_record_from_a_newer_build_still_opens_read_only(tmp_path):
    payload = json.loads(json.dumps(LEGACY_METADATA))
    payload["versions"][0]["a_key_this_build_never_heard_of"] = {"nested": True}
    path = tmp_path / "newer.json"
    path.write_text(json.dumps(payload), encoding="utf-8")

    from app.rag.indexing import IndexRegistry

    registry = IndexRegistry(path, scope=_scope(MODEL_A, DIM_WIDE))

    assert registry.current(INDEX).index_version_id == payload["current"][INDEX]


def test_a_record_missing_a_field_this_build_needs_fails_loudly(tmp_path):
    payload = json.loads(json.dumps(LEGACY_METADATA))
    del payload["versions"][0]["checksum"]
    path = tmp_path / "broken.json"
    path.write_text(json.dumps(payload), encoding="utf-8")

    from app.rag.indexing import IndexRegistry

    with pytest.raises(ValueError, match="missing required field"):
        IndexRegistry(path, scope=_scope(MODEL_A, DIM_WIDE))

# --------------------------------- the profile is read live, not frozen at import time
def test_editing_the_embedder_constant_moves_the_configured_profile(tmp_path, monkeypatch):
    import app.rag.retriever as retriever_module
    from app.rag.indexing import IndexRegistry, configured_embedding_scope

    monkeypatch.delenv("EMBEDDING_MODEL", raising=False)
    original = retriever_module.EMBED_MODEL
    assert configured_embedding_scope().embedding_model == original

    registry = IndexRegistry(tmp_path / "indexes.json")
    before = _version(registry, chunks=1)
    registry.publish(before.index_version_id)
    assert before.embedding_model == original

    monkeypatch.setattr(retriever_module, "EMBED_MODEL", "upgraded-embed-v2")
    # No restart, no re-import: the same live registry now means a different profile.
    assert registry.scope.embedding_model == "upgraded-embed-v2"

    from app.rag.indexing import CODE_MODEL_DRIFT, IndexScopeError

    with pytest.raises(IndexScopeError) as refused:
        registry.validate(before.index_version_id)
    assert refused.value.code == "embedding_scope_mismatch"
    assert CODE_MODEL_DRIFT in refused.value.codes


def test_the_declared_width_can_be_configured_without_touching_code(tmp_path, monkeypatch):
    from app.rag.indexing import IndexRegistry, configured_embedding_scope

    monkeypatch.setenv("EMBEDDING_MODEL", "remote-embed")
    monkeypatch.setenv("EMBEDDING_DIMENSION", "1024")
    scope = configured_embedding_scope()
    assert (scope.embedding_model, scope.dimension) == ("remote-embed", 1024)

    registry = IndexRegistry(tmp_path / "indexes.json")
    version = _version(registry, chunks=1)
    assert (version.embedding_model, version.dimension) == ("remote-embed", 1024)

    monkeypatch.setenv("EMBEDDING_DIMENSION", "not-a-number")
    # An unusable declaration falls back to the shipped width, loudly, rather than to "any".
    assert configured_embedding_scope().dimension == DIM_WIDE


def test_the_shipped_default_describes_the_model_that_is_actually_called():
    """The two copies of the model name cannot drift apart unnoticed."""
    import app.rag.retriever as retriever_module
    from app.rag.indexing import DEFAULT_EMBEDDING_DIMENSION, DEFAULT_EMBEDDING_MODEL

    assert DEFAULT_EMBEDDING_MODEL == retriever_module.EMBED_MODEL
    assert DEFAULT_EMBEDDING_DIMENSION == 768


# ------------------------------------------------------- drift, for a health check to read
def test_drift_names_the_axis_that_moved_and_the_versions_affected(tmp_path):
    registry = _registry(tmp_path, model=MODEL_A, dimension=DIM_WIDE)
    clean = _version(registry, source="policy.txt|v1")
    registry.publish(clean.index_version_id)

    settled = registry.embedding_drift()
    assert settled.drifted is False
    assert settled.codes == ()
    assert settled.checked == 1

    registry._fixed_scope = _scope(MODEL_B, DIM_WIDE)
    drifted = registry.embedding_drift()
    assert drifted.drifted is True
    assert drifted.codes == ("embedding_model_drift",)
    assert drifted.affected_index_version_ids == (clean.index_version_id,)
    assert drifted.configured == _scope(MODEL_B, DIM_WIDE)
    assert drifted.as_dict()["codes"] == ["embedding_model_drift"]

    registry._fixed_scope = _scope(MODEL_B, DIM_NARROW)
    both = registry.embedding_drift()
    assert set(both.codes) == {"embedding_model_drift", "embedding_dimension_drift"}

    _load_legacy(tmp_path, registry)
    unknown = registry.embedding_drift()
    assert "embedding_scope_unknown" in unknown.codes
    assert set(unknown.unknown_index_version_ids) == set(LEGACY_METADATA["current"].values())


def test_the_publisher_binds_every_publication_it_makes(tmp_path):
    from app.rag.indexing import DocumentIndexPublication, IndexPublisher

    registry = _registry(tmp_path, model=MODEL_A, dimension=DIM_WIDE)
    publisher = IndexPublisher(registry, store=None)
    outcome = publisher.publish(
        DocumentIndexPublication(filename="policy.txt", version=1, chunks=("one", "two"))
    )

    assert outcome.embedding_model == MODEL_A
    assert outcome.dimension == DIM_WIDE
    assert outcome.as_dict()["dimension"] == DIM_WIDE
    assert registry.current(INDEX).scope == _scope(MODEL_A, DIM_WIDE)

    # Moving the config half-way through cannot relabel a publication: create, validate and
    # publish all use the one scope the publisher resolved at the start.
    registry._fixed_scope = _scope(MODEL_B, DIM_WIDE)
    second = publisher.publish(
        DocumentIndexPublication(filename="policy.txt", version=2, chunks=("one", "two"))
    )
    assert second.embedding_model == MODEL_B
    assert second.previous_index_version_id == outcome.index_version_id


def test_an_aborted_publication_forgets_its_own_version_even_over_a_legacy_current(tmp_path):
    """A scope gate must not turn a rollback refusal into a stranded version.

    Before this change the two undo steps shared one try, so a refused rollback skipped the
    discard and left a version in the registry that nobody had published.
    """
    from app.rag.indexing import DocumentIndexPublication, IndexPublisher, IndexRegistry

    registry = _registry(tmp_path, model=MODEL_A, dimension=DIM_WIDE)
    _load_legacy(tmp_path, registry)
    legacy_id = LEGACY_METADATA["current"][INDEX]
    publisher = IndexPublisher(registry, store=None)

    def refuse(index_version_id):
        raise RuntimeError("the index metadata file is read only")

    registry.publish = refuse
    with pytest.raises(Exception):
        publisher.publish(
            DocumentIndexPublication(filename="policy.txt", version=2, chunks=("one", "two"))
        )

    assert legacy_id in registry._versions
    assert len(registry._versions) == 2
    assert registry.current(INDEX).index_version_id == legacy_id


class _RecordingConnection:
    def __init__(self):
        self.calls = []

    def execute(self, sql, params=()):
        self.calls.append((" ".join(str(sql).split()), params))
        return self

    def fetchone(self):
        return None


def test_the_mirror_records_the_profile_on_the_version_row(tmp_path):
    from app.rag.indexing import (
        DocumentIndexPublication,
        IndexMirrorSession,
        IndexVersion,
    )

    connection = _RecordingConnection()
    session = IndexMirrorSession(connection, counters_enabled=False)
    publication = DocumentIndexPublication(filename="policy.txt", version=1, chunks=("one",))
    version = IndexVersion(
        index_version_id="document:policy.txt:v1",
        index_id=INDEX,
        source_version_id="policy.txt|v1",
        backend="chroma",
        chunk_count=1,
        checksum="a" * 64,
        status="building",
        created_at="2026-09-18T00:00:00+00:00",
        embedding_model=MODEL_B,
        dimension=DIM_NARROW,
    )

    session.insert_version(publication, version)

    sql, params = connection.calls[0]
    assert "INSERT INTO index_versions" in sql
    metadata = json.loads(params[-1])
    assert metadata["embedding_model"] == MODEL_B
    assert metadata["dimension"] == DIM_NARROW


def test_a_build_that_cannot_name_a_profile_refuses_to_publish(tmp_path):
    """The fallback is a declared default, never silence.

    With no model to record there is nothing to bind, and a version that claims a profile it
    cannot name is precisely the false guarantee R22 removes.
    """
    from app.rag.indexing import EmbeddingScope, IndexRegistry

    registry = IndexRegistry(tmp_path / "indexes.json", scope=EmbeddingScope(None, None))

    with pytest.raises(ValueError, match="embedding model and a positive dimension"):
        _version(registry, chunks=1)


def test_a_health_probe_can_read_the_binding_without_touching_the_filesystem(tmp_path):
    from app.rag.indexing import embedding_drift_from_metadata, read_index_metadata

    metadata = tmp_path / "nested" / "deeper" / "index-versions.json"
    metadata.parent.mkdir(parents=True)
    metadata.write_text(json.dumps(LEGACY_METADATA), encoding="utf-8")
    before = metadata.read_bytes()

    versions, current = read_index_metadata(metadata)
    assert len(versions) == 2 and len(current) == 2

    drift = embedding_drift_from_metadata(metadata, scope=_scope(MODEL_A, DIM_WIDE))
    assert drift.drifted is True
    assert drift.codes == ("embedding_scope_unknown",)
    assert drift.checked == 2
    assert metadata.read_bytes() == before


def test_a_missing_metadata_file_reports_nothing_rather_than_creating_it(tmp_path):
    from app.rag.indexing import embedding_drift_from_metadata

    missing = tmp_path / "never-created" / "index-versions.json"

    drift = embedding_drift_from_metadata(missing, scope=_scope(MODEL_A, DIM_WIDE))

    assert drift.drifted is False
    assert drift.checked == 0
    assert not missing.parent.exists()